; CP/M profile with bundled application disks mounted.

[system]
title = vZ80 CP/M Apps

[console]
terminal = adm3a
boot_text = "dir\r"

[disks]
a    = /altair48k-boot.dsk
b    = /floppy1.dsk
c    = /floppy2.dsk
d    = /wordstar.dsk
boot = a
