; Minimal CP/M profile.

[system]
title = vZ80 Basic CP/M
prom      = /icom-prom.bin
prom_addr = 0xF000

[console]
terminal = adm3a
boot_text = ""

[disks]
a    = /altair48k-boot.dsk
b    = /floppy1.dsk
c    =
d    =
boot = a
