; CP/M profile with bundled application disks mounted.

[system]
title = vZ80 CP/M Apps
prom      = /icom-prom.bin
prom_addr = 0xF000

[console]
terminal = adm3a
boot_text = "dir\r"

[disks]
a    = /altair48k-boot.dsk
b    = /floppy1.dsk
c    = /wordstar.dsk
d    = /scalc.dsk
boot = a
